[build]
command = "npm run build"
publish= "/build"
base = "/"


[[redirects]]
from = "/api/*"
to = "http://158.220.97.101:4000/api/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200